- name: download nsq
  get_url:
    url: "https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.2.0.linux-amd64.go1.12.9.tar.gz"
    dest: "/root/nsq-1.2.0.linux-amd64.go1.12.9.tar.gz"

- name: extract nsq
  unarchive:
    dest: /root
    src: "/root/nsq-1.2.0.linux-amd64.go1.12.9.tar.gz"
    creates: "/usr/local/nsq-1.2.0.linux-amd64.go1.12.9"
    remote_src: true

- name: move to local
  command: mv /root/nsq-1.2.0.linux-amd64.go1.12.9 /usr/local/nsq

- name: add to path
  copy:
    dest: /etc/profile.d/nsq.sh
    content: 'PATH=$PATH:/usr/local/nsq/bin'

- name: Create /etc/nsq
  file:
    path: /etc/nsq
    state: directory

- name: Create /etc/nsq
  file:
    path: /var/lib/nsq
    state: directory

- name: copy nsqd.conf
  copy:
    src: ../files/nsqd.conf
    dest: /etc/nsq/nsqd.conf
    mode: 0644
    backup: yes

- name: copy nsqd.service
  copy:
    src: ../files/nsqd.service
    dest: /lib/systemd/system/nsqd.service
    mode: 0755
    backup: yes

- name: enable nsqd.service
  systemd:
    name: nsqd.service
    enabled: yes

- name: start nsqd.service
  systemd:
    name: nsqd.service
    state: started

- name: copy nsqlookupd.conf
  copy:
    src: ../files/nsqlookupd.conf
    dest: /etc/nsq/nsqlookupd.conf
    mode: 0644
    backup: yes

- name: copy nsqlookupd.service
  copy:
    src: ../files/nsqlookupd.service
    dest: /lib/systemd/system/nsqlookupd.service
    mode: 0755
    backup: yes

- name: enable nsqlookupd.service
  systemd:
    name: nsqlookupd.service
    enabled: yes

- name: start nsqlookupd.service
  systemd:
    name: nsqlookupd.service
    state: started

- name: copy nsqadmin.conf
  copy:
    src: ../files/nsqadmin.conf
    dest: /etc/nsq/nsqadmin.conf
    mode: 0644
    backup: yes

- name: copy nsqadmin.service
  copy:
    src: ../files/nsqadmin.service
    dest: /lib/systemd/system/nsqadmin.service
    mode: 0755
    backup: yes

- name: enable nsqadmin.service
  systemd:
    name: nsqadmin.service
    enabled: yes

- name: start nsqadmin.service
  systemd:
    name: nsqadmin.service
    state: started
