- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.small
    role: analyticsserver
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-07b0f924d6ce61fc4
    volume_size: 15
    hostgroups: analyticsservers
  roles:
  - ec2

- hosts: analyticsservers
  become: yes
  vars:
    nginx_startup_file: analytics.js
    node_major: 14
    node_minor: 15
    node_patch: 1
  roles:
  - base
  - ntpd
  - nodejs
  - app
  - ruby
  - passenger
  - pm2

- hosts: local
  connection: local
  gather_facts: false
  vars:
    elb_group: analyticsservers
    region: us-east-1
  roles:
  - elb
