- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.small
    role: analyticsserver
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-07b0f924d6ce61fc4
    volume_size: 15
    hostgroups: analyticsservers
  roles:
  - ec2

- hosts: analyticsservers
  become: yes
  vars:
    elb_group: analyticsservers
    java_version: 1.8.0
    scala_version: 2.13.4
    go_version: 1.15.6
    sbt_version: 1.4.6
  roles:
  - base
  - ntpd
  - scala
  - go
  - nsq
  - snowplow
