- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.medium
    role: dbserver
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-44a2fa35
    volume_size: 20
    hostgroups: dbservers
  roles:
  - ec2

- hosts: dbservers
  become: true
  roles:
  - base
  - ntpd
  - python
  - awscli
  - postgresql
