# - hosts: localhost
#   connection: local
#   gather_facts: false
#   vars:
#     image: ami-02eac2c0129f6376b
#     instance_type: t3.medium
#     role: logserver
#     group_ids:
#       - sg-0589cb45cd2b71602
#       - sg-06900206f0341c58c
#     volume_size: 20
#     hostgroups: logservers
#   roles:
#   - ec2
#
- hosts: logservers
  become: yes
  roles:
  # - base
  # - ntpd
  # - openjdk
  # - mongodb
  # - elasticsearch
  - graylog
