- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.small
    role: webserver
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-07f2dc04339e6b7a8
    volume_size: 10
    hostgroups: webservers
  roles:
  - ec2

- hosts: webservers
  become: yes
  vars:
    node_major: 10
    node_minor: 23
    node_patch: 0
  roles:
  - base
  - ntpd
  - nodejs
  - nginx
  - web
