- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.small
    role: webservers
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-07f2dc04339e6b7a8
    volume_size: 15
    hostgroups: webservers
  roles:
  - ec2

- hosts: webservers
  become: yes
  vars:
    nginx_startup_file: web.js
    node_major: 14
    node_minor: 15
    node_patch: 1
  roles:
  - base
  - ntpd
  - nodejs
  - app
  - ruby
  - passenger

- hosts: local
  connection: local
  gather_facts: false
  vars:
    elb_group: webservers
    region: us-east-1
  roles:
  - elb
