- name: install libcurl
  yum:
    name: libcurl-devel

- name: install passenger
  shell: 'bash -lc "gem install passenger -v 6.0.4"'

- name: install nginx
  shell: 'bash -lc "passenger-install-nginx-module --auto --auto-download --languages nodejs"'

- name: copy nginx
  copy:
    src: ./nginx
    dest: /etc/init.d/nginx
    mode: 0755

- name: copy nginx.conf
  copy:
    src: ./nginx.conf
    dest: /opt/nginx/conf/nginx.conf
    mode:
    backup: yes

- name: copy nginx.logrotate
  copy:
    src: ./nginx.logrotate
    dest: /etc/logrotate.d/nginx

- name: enable nginx
  systemd:
    name: nginx
    daemon_reload: yes

- name: enable nginx
  systemd:
    name: nginx
    enabled: yes

- name: start nginx
  systemd:
    name: nginx
    state: started
