- name: clone enrich
  shell:
    cmd: 'git clone https://github.com/snowplow/enrich.git'
    chdir: /opt

- name: build enrich
  shell:
    cmd: 'sbt "project nsq" assembly'
    chdir: /opt/enrich

- name: copy snowplow-stream-collector.hocon
  template:
    src: ../files/snowplow-enrich.hocon
    dest: /opt/enrich/modules/nsq/target/scala-2.12/snowplow-enrich.hocon
    backup: yes

- name: copy resolver.json
  copy:
    src: ../files/resolver.json
    dest: /opt/enrich/modules/nsq/target/scala-2.12/resolver.json
    backup: yes

- name: copy enrichments
  copy:
    src: ../files/enrichments
    dest: /opt/enrich/modules/nsq/target/scala-2.12/
    backup: yes

- name: copy enirch.service
  copy:
    src: ../files/enirch.service
    dest: /lib/systemd/system/enirch.service
    mode: 0755
    backup: yes

- name: enable enirch.service
  systemd:
    name: enirch.service
    enabled: yes

- name: start enirch.service
  systemd:
    name: enirch.service
    state: started
