version: 2.1
executors:
  node-postgres:
    docker:
      - image: circleci/node:8.14.0
        environment:
            DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
            POSTGRES_PASSWORD: ""
    working_directory: ~/repo
jobs:
  test:
    executor: node-postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  build:
    executor: node-postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: NODE_ENV=production npm run build
      - run: NODE_ENV=production npm run help
  deploy:
    executor: node-postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "22:d3:aa:30:bb:b0:7e:f7:68:58:e0:fe:a9:4e:b3:0b"
      - run: npm run deploy
workflows:
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
