version: 2.1
executors:
  node-postgres:
    docker:
      - image: circleci/node:14.15.1
        environment:
            DATABASE_URL: postgresql://root@localhost/circle_test
            REDIS_URL: redis://127.0.0.1:6379/14
      - image: circleci/postgres:10-alpine-ram
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
            POSTGRES_PASSWORD: ""
      - image: circleci/redis:6.0-alpine3.13
    working_directory: ~/repo
jobs:
  test:
    executor: node-postgres
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: NODE_ENV=test npm run maha test
  deploy:
    executor: node-postgres
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - 0d:79:bf:2b:27:c2:17:a2:ac:17:89:66:17:66:8a:50
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - attach_workspace:
          at: ~/repo/root
      - run:
          name: Install rsync
          command: sudo apt-get install rsync
      - run:
          name: Deploy code
          command: NODE_ENV=production npm run maha shipit deploy
workflows:
  test-stage-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
