- name: Install git
  yum:
    name: git

- name: copy deploy
  copy:
    src: ./deploy
    dest: /home/centos/.ssh/deploy

- name: copy config
  copy:
    src: ./config
    dest: /home/centos/.ssh/config

- name: Create releases
  file:
    path: /var/www/app/releases
    state: directory

- name: Create shared directories
  file:
    owner: centos
    group: centos
    mode: 0777
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/www/app/shared/tmp
    - /var/www/app/shared/imagecache
    - /var/www/app/shared/logs
