- hosts: workers
  become: yes
  tasks:

    - name: install base
      include: ../playbooks/base/main.yml

    - name: install ntpd
      include: ../playbooks/ntpd/main.yml

    - name: install devtoolset
      include: ../playbooks/devtoolset/main.yml

    - name: install nodejs
      include: ../playbooks/nodejs/main.yml

    - name: install libreoffice
      include: ../playbooks/libreoffice/main.yml

    - name: install app
      include: ../playbooks/app/main.yml

    - name: install clamav
      include: ../playbooks/clamav/main.yml
