- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.small
    role: appserver
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-40aef631
    volume_size: 15
    hostgroups: appservers
  roles:
  - ec2

- hosts: appservers
  become: yes
  roles:
  - base
  - ntpd
  - devtoolset
  - nodejs
  - libreoffice
  - app
  - ruby
  - passenger

- hosts: local
  connection: local
  gather_facts: false
  vars:
    region: us-east-1
  roles:
  - elb
