- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    image: ami-02eac2c0129f6376b
    instance_type: t3.small
    role: cacheserver
    group_ids:
      - sg-0589cb45cd2b71602
      - sg-0280ab1bb91065d82
    volume_size: 10
    hostgroups: cacheservers
  roles:
  - ec2

- hosts: cacheservers
  become: true
  roles:
  - base
  - ntpd
  - devtoolset
  - redis
