- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_type: t3.medium
    region: us-east-1
    groups:
      - all
      - dbservers
  roles:
  - ec2

- hosts: dbservers
  become: true
  roles:
  - base
  - ntpd
  - postgresql
