- name: Extract haproxy
  unarchive:
    src: http://www.haproxy.org/download/1.9/src/haproxy-1.9.7.tar.gz
    dest: /home/centos
    remote_src: yes

- name: Build haproxy
  shell: make TARGET=linux2628 USE_OPENSSL=1 && make install
  args:
    chdir: /home/centos/haproxy-1.9.7

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/lib/haproxy
    - /etc/haproxy

- name: Touch stats
  file:
    path: /var/lib/haproxy/stats
    state: touch

- name: Symlink haproxy
  file:
    src: /usr/local/sbin/haproxy
    dest: /usr/sbin/haproxy
    state: link

- name: copy haproxy.service
  copy:
    src: ./haproxy.service
    dest: /etc/init.d/haproxy
    mode: 0755
    backup: yes

- name: Add user haproxy
  user:
    name: haproxy

- name: copy haproxy.cfg
  copy:
    src: ./haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

- name: copy mahaplatform.com.pem
  copy:
    src: ../../../keys/mahaplatform.com.pem
    dest: /etc/pki/tls/private/mahaplatform.com.pem

- name: enable haproxy
  systemd:
    name: haproxy
    daemon_reload: yes

- name: enable haproxy
  systemd:
    name: haproxy
    enabled: yes

- name: start haproxy
  systemd:
    name: haproxy
    state: started
