- name: install nptd
  yum:
    name: ntp
    state: latest

- name: configure nptd
  shell:
    cmd: 'ntpdate -s time.nist.gov'

- name: reload ntpd
  systemd:
    name: ntpd
    daemon_reload: yes

- name: enable ntpd
  systemd:
    name: ntpd
    enabled: yes

- name: start ntpd
  systemd:
    name: ntpd
    state: started

- name: Remove localtime
  file:
    path: /etc/localtime
    state: absent

- name: Symlink eastern time
  file:
    src: /usr/share/zoneinfo/US/Eastern
    dest: /etc/localtime
    state: link
