- name: clone collector
  shell:
    cmd: 'git clone https://github.com/snowplow/stream-collector.git'
    chdir: /opt

- name: build collector
  shell:
    cmd: 'sbt "project nsq" assembly'
    chdir: /opt/stream-collector

- name: copy snowplow-stream-collector.hocon
  copy:
    src: ../files/snowplow-stream-collector.hocon
    dest: /opt/stream-collector/nsq/target/scala-2.12/snowplow-stream-collector.hocon
    backup: yes

- name: copy collector.service
  copy:
    src: ../files/collector.service
    dest: /lib/systemd/system/collector.service
    mode: 0755
    backup: yes

- name: enable collector.service
  systemd:
    name: collector.service
    enabled: yes

- name: start collector.service
  systemd:
    name: collector.service
    state: started
