- name: "add server to {{elb_group}} elb target group"
  elb_target:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    target_group_name: "{{elb_group}}"
    target_id: "{{ item.id }}"
    region: "{{ aws_region }}"
    state: present
  with_items: "{{ hostvars['localhost']['ec2'].instances }}"
