- name: install pm2
  shell:
    cmd: 'npm install -g pm2'

- name: start pm2
  shell:
    cmd: 'bash -lc "NODE_ENV=production pm2 startOrRestart ./current/ecosystem.config.js"'
  args:
    chdir: /var/www/app
