- name: copy deploy
  copy:
    src: ../files/deploy
    dest: /root/.ssh/deploy
    owner: root
    group: root
    mode: 0600

- name: copy config
  copy:
    src: ../files/config
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: 0600

- name: create releases directory
  file:
    path: /var/www/maha/releases
    state: directory

- name: create shared directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - /var/www/maha/shared/imagecache
    - /var/www/maha/shared/maxmind
    - /var/www/maha/shared/logs
    - /var/www/maha/shared/tmp
    - /var/www/maha/shared/web

- name: create temp release
  file:
    path: '/var/www/maha/releases/{{ansible_date_time.iso8601_basic_short}}/public'
    state: directory

- name: copy index.html
  copy:
    src: ../files/index.html
    dest: '/var/www/maha/releases/{{ansible_date_time.iso8601_basic_short}}/public/index.html'

- name: symlink current
  file:
    src: /var/www/maha/releases/{{ansible_date_time.iso8601_basic_short}}
    dest: /var/www/maha/current
    state: link
