- name: install git
  yum:
    name: git

- name: copy deploy
  copy:
    src: ../files/deploy
    dest: /root/.ssh/deploy
    owner: root
    group: root
    mode: 0600

- name: copy config
  copy:
    src: ../files/config
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: 0600

- name: create releases directory
  file:
    path: /var/www/app/releases
    state: directory

- name: create shared directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - /var/www/app/shared/tmp
    - /var/www/app/shared/imagecache
    - /var/www/app/shared/logs

- name: clone master
  git:
    repo: https://github.com/mahaplatform/mahaplatform.com.git
    dest: /var/www/app/repo
    update: yes
    force: no

- name: get new tags
  shell:
    cmd: 'git fetch --tags'
  args:
    chdir: /var/www/app/repo

- name: get lastest tag
  shell:
    cmd: 'git describe --tags `git rev-list --tags --max-count=1`'
  args:
    chdir: /var/www/app/repo
  register: latest_tag

- name: clone lastest tag
  git:
    repo: https://github.com/mahaplatform/mahaplatform.com.git
    dest: /var/www/app/repo
    version: "{{ latest_tag.stdout }}"

- name: write simple .env
  template:
    src: ../files/.env.j2
    dest: /var/www/app/repo/.env

- name: install node_modules
  shell:
    cmd: 'npm install'
  args:
    chdir: /var/www/app/repo

- name: write full .env
  shell:
    cmd: 'NODE_ENV=production npm run env'
  args:
    chdir: /var/www/app/repo

- name: build src
  shell:
    cmd: 'NODE_ENV=production npm run build'
  args:
    chdir: /var/www/app/repo

- name: copy src
  shell:
    cmd: 'cp -rp /var/www/app/repo/dist /var/www/app/releases/{{ansible_date_time.iso8601_basic_short}}'

- name: install node_modules
  shell:
    cmd: 'npm install'
  args:
    chdir: "/var/www/app/releases/{{ansible_date_time.iso8601_basic_short}}"

- name: symlink logs
  file:
    src: /var/www/app/shared/logs
    dest: /var/www/app/releases/{{ansible_date_time.iso8601_basic_short}}/logs
    state: link

- name: symlink tmp
  file:
    src: /var/www/app/shared/tmp
    dest: /var/www/app/releases/{{ansible_date_time.iso8601_basic_short}}/tmp
    state: link

- name: symlink imagecache
  file:
    src: /var/www/app/shared/imagecache
    dest: /var/www/app/releases/{{ansible_date_time.iso8601_basic_short}}/public/imagecache
    state: link

- name: symlink current
  file:
    src: /var/www/app/releases/{{ansible_date_time.iso8601_basic_short}}
    dest: /var/www/app/current
    state: link
