- name: clone collector
  shell:
    cmd: 'git clone https://github.com/snowplow/stream-collector.git'
    chdir: /opt

- name: build collector
  shell:
    cmd: 'sbt "project nsq" assembly'
    chdir: /opt/stream-collector

- name: copy snowplow-stream-collector.hocon
  copy:
    src: ../files/snowplow-stream-collector.hocon
    dest: /opt/stream-collector/nsq/target/scala-2.12/snowplow-stream-collector.hocon
    backup: yes

# - name: copy collector.init
#   copy:
#     src: ../files/collector.init
#     dest: /etc/init.d/collector
#     mode: 0755
#     backup: yes
#
# - name: clone enrich
#   shell:
#     cmd: 'git clone https://github.com/snowplow/enrich.git'
#     chdir: /opt
#
# - name: build enrich
#   shell:
#     cmd: 'sbt "project nsq" assembly'
#     chdir: /opt/enrich
