- name: provision instance(s)
  ec2:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    key_name: mahaplatform
    group_id: "{{ group_ids }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    region: "{{ aws_region }}"
    wait: true
    count: 1
    zone: "{{ aws_zone }}"
    termination_protection: yes
    volumes:
      - device_name: /dev/sdb
        volume_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
  register: ec2

- name: add host to inventory
  add_host:
    name: "{{ item.public_ip }}"
    groups: "{{ hostgroups }}"
  with_items: "{{ ec2.instances }}"

- name: set hostname
  set_fact:
    hostname: "{{ role }}-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}.mahaplatform.com"

- name: tag instance
  ec2_tag:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{ aws_region }}"
    resource: "{{ item.id }}"
    state: present
    tags:
      Name: "{{ hostname }}"
      Role: "{{ role }}"
  with_items: "{{ ec2.instances }}"

- name: configure dns
  route53:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    state: present
    zone: mahaplatform.com
    record: "{{ hostname }}"
    type: "A"
    ttl: 3600
    value: "{{ item.public_ip }}"
    wait: true
  with_items: "{{ ec2.instances }}"

- name: wait for instance
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
