- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - cairo
    - cairo-devel
    - libjpeg-devel

- name: Install nodejs
  yum:
    name: https://rpm.nodesource.com/pub_8.x/el/6/x86_64/nodejs-8.14.0-1nodesource.x86_64.rpm
