- name: install python-pip
  yum:
    pkg: python-pip
    state: latest

- name: install awscli
  pip:
    name: awscli
    state: latest

- name: create .aws directory
  file:
    path: /home/centos/.aws
    state: directory
    owner: centos
    group: centos
    mode: 0755

- name: create config
  template:
    src: ../files/config
    dest: /home/centos/.aws/config
    owner: centos
    group: centos
    mode: 0600

- name: create credentials
  template:
    src: ../files/credentials
    dest: /home/centos/.aws/credentials
    owner: centos
    group: centos
    mode: 0600
