- name: extract redis
  unarchive:
    src: https://s3.amazonaws.com/ansible.mahaplatform.com/redis-4.0.0.tar.gz
    dest: /root
    remote_src: yes

- name: build redis dependencies
  shell:
    cmd: 'make hiredis jemalloc linenoise lua'
  args:
    chdir: /root/redis-4.0.0/deps

- name: build redis
  shell:
    cmd: 'make && make install'
  args:
    chdir: /root/redis-4.0.0

- name: copy redis-setup.sh
  copy:
    src: ../files/redis-setup.sh
    dest: /root/redis-4.0.0/utils/redis-setup.sh
    mode: 0755

- name: run redis setup
  shell:
    cmd: './redis-setup.sh'
  args:
    chdir: /root/redis-4.0.0/utils
