- name: add ssh keys
  copy:
    src: ../files/authorized_keys
    dest: /home/centos/.ssh/authorized_keys

- name: update yum
  yum:
    name: "*"
    state: latest

- name: install epel-release
  yum:
    name:
    - epel-release
    state: present

- name: install wget
  yum:
    name: wget

- name: install msttcore fonts
  yum:
    name: https://www.itzgeek.com/msttcore-fonts-2.0-3.noarch.rpm
