import { Fixtures } from 'maha'

const resourcesFixtures = new Fixtures({
  tableName: 'competencies_resources',
  records: [
    {
      id: 1,
      team_id: 1,
      title: 'HR Benefits Session',
      description: 'Benefits Session with HR rep (arranged with all eligible staff)',
      url: 'Contact Krystal Dunn or Theresa Emerick.',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.702Z',
      updated_at: '2017-10-24T18:33:08.702Z'
    },
    {
      id: 2,
      team_id: 1,
      title: 'Cornell Online Benefits Info',
      description: 'MyCCE Orientation and Dashboard; Cornell Online Benefits information',
      url: 'http://staff.cce.cornell.edu/human_resources/Pages/BenefitsIndex.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.702Z',
      updated_at: '2017-10-24T18:33:08.702Z'
    },
    {
      id: 3,
      team_id: 1,
      title: 'Orientation Check List',
      description: 'Complete orientation checklist',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.702Z',
      updated_at: '2017-10-24T18:33:08.702Z'
    },
    {
      id: 4,
      team_id: 1,
      title: 'CCETC Orientation Presentation',
      description: null,
      url: 'Contact Krystal Dunn for dates of next session.',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.702Z',
      updated_at: '2017-10-24T18:33:08.702Z'
    },
    {
      id: 5,
      team_id: 1,
      title: 'Online Resources re: basic CCETCs HR, building and safety policies',
      description: null,
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 6,
      team_id: 1,
      title: 'New Staff Orientation on Campus',
      description: 'On-campus CCE orientation provides new employees with CCE history, mission and structure. There are two levels, based on classification of the employee. Registration required.',
      url: 'http://staff.cce.cornell.edu/Pages/home.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 7,
      team_id: 1,
      title: 'New Staff Orientation Pre-Recorded Session',
      description: 'CCE Administration offers two pre-recorded webinars (with Powerpoint presentations) for new employees.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Course-Description2.aspx?courseid=75',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 8,
      team_id: 1,
      title: 'MyCCE Orientation Materials',
      description: 'Web-based information about CCE-Tompkins history',
      url: 'https://mycce.me/content/about-ccetc-history-and-ethos',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 9,
      team_id: 1,
      title: 'MyCCE Orientation Materials - CCETC Strategic Plan',
      description: 'Full strategic plan for employees to review',
      url: 'https://mycce.me/content/my-hr-forms-and-references-tompkins-strategic-plan-prologue',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 10,
      team_id: 1,
      title: 'CCE Orientation Guide for Supervisors',
      description: 'Information from CCE Administration to assist with orientation of new employees',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/newstafforientation.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 11,
      team_id: 1,
      title: 'CCETC Additional Orientation Resources for Supervisors',
      description: 'Additional association-based resources to assist CCETC supervisors with orientation of new employees',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 12,
      team_id: 1,
      title: 'MyCCE Supervisor Materials',
      description: 'Multiple resources for supervisor use. May require in person review with HR or Issue Leader.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/newstafforientation.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 13,
      team_id: 1,
      title: 'CCE Administration Supervisor Orientation',
      description: 'Campus-based training for new CCE supervisors',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Course-Description2.aspx?courseid=114',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 14,
      team_id: 1,
      title: 'Risk Management Training during All-Staff',
      description: 'All-Staff Mtg Safety Updates',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 15,
      team_id: 1,
      title: 'Workplace Violence Training',
      description: 'In-person training for new employees - covers statistics about violence in the workplace, warning signs and avoidance techniques',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 16,
      team_id: 1,
      title: 'CCE Professional Development Resources',
      description: 'Online resources on a variety of risk-management topics, including summer programming, volunteer risk management and specialized 4-H and youth protection topics',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/risk.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 17,
      team_id: 1,
      title: 'Sexual Harassment/Workplace Harassment Training',
      description: 'In-person training on policies and laws (required every 2 years for all employees)',
      url: 'Contact HR office for next scheduled training. ',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 18,
      team_id: 1,
      title: 'CU Learn online tutorial',
      description: '\'Building a Culture of Respect: Responding to Sexual Harrassment, Violence and DIscrimination\' online tutorial takes approximately 45-60 minutes to complete. Free with a Cornell Net ID.',
      url: 'https://cornell.sabacloud.com/Saba/Web_spf/NA1PRD0089/common/ledetail/cours000000000003585',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 19,
      team_id: 1,
      title: 'Civil Rights Training',
      description: 'Civil Rights Training is provided annually via webinar by CCE Admin personnel (offered summer and fall).',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Training.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 20,
      team_id: 1,
      title: 'CCE Resources on Diversity, Inclusion, and EPO',
      description: 'The CCE Administrations website with recorded webinars and other resources re: diversity and inclusion',
      url: 'http://www.staff.cce.cornell.edu/orgdev/Pages/diversity.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 21,
      team_id: 1,
      title: 'CCE Tompkins Diversity Statement and Committee',
      description: 'Web-based information related to CCE-Tompkins policies and goals',
      url: 'http://ccetompkins.org/diversity',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 22,
      team_id: 1,
      title: 'CCE Tompkins Policy Manual',
      description: 'The manual reviews all employee benefits and policies related to them (except EAP and Vision Coverage)',
      url: 'http://ccetompkins.org/about-us/human-resource-policy-manual',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.703Z'
    },
    {
      id: 23,
      team_id: 1,
      title: 'MyCCE',
      description: 'Information about employee benefits and support services',
      url: 'https://mycce.me/content/my-hr-forms-and-tools-for-employee-use',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.703Z',
      updated_at: '2017-10-24T18:33:08.704Z'
    },
    {
      id: 24,
      team_id: 1,
      title: 'Employee Assistance Program (confidential counseling)',
      description: 'Info about CCETCs Employee Assistance Program (EAP) based at Family and Childrens Services and how to access it',
      url: 'http://www.fcsith.org/eap/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.704Z',
      updated_at: '2017-10-24T18:33:08.704Z'
    },
    {
      id: 25,
      team_id: 1,
      title: 'Employee Assistance Program (workshops & trainings)',
      description: 'Employees may attend EAP Seminars on the following topics: Time Management and Achieving Work-Life Balance, Keeping Your Cool: Resolving Conflict in the Workplace. Staff can attend at Family and Childrens Services or, if there is enough interest, the programs can be offered on location. (there is a cost- $150 per hour if offered onsite)',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.704Z',
      updated_at: '2017-10-24T18:33:08.704Z'
    },
    {
      id: 26,
      team_id: 1,
      title: 'CCE Professional Development Webinar',
      description: 'Change Burn-Out and Stress to Job Satisfaction: Taking Charge of You\' (free webinar)',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Course-Description2.aspx?courseid=69',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.704Z',
      updated_at: '2017-10-24T18:33:08.704Z'
    },
    {
      id: 27,
      team_id: 1,
      title: 'Lynda.com - Business: Business Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Powerless to Powerful: Taking Control; Learning to Be Assertive; Managing Stress; Building Resiliance; Building Self-Confidence',
      url: 'https://it.cornell.edu/lynda',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.704Z',
      updated_at: '2017-10-24T18:33:08.704Z'
    },
    {
      id: 28,
      team_id: 1,
      title: 'Skillport - Business Skills: Communications Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Example: Recognizing Conflict in the Workplace',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.704Z',
      updated_at: '2017-10-24T18:33:08.704Z'
    },
    {
      id: 29,
      team_id: 1,
      title: 'TED Talk',
      description: 'Free online videos on a variety of topics, ranging from informational to inspirational. Example: How to Make Stress Your Friend',
      url: 'https://www.ted.com/talks',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 30,
      team_id: 1,
      title: 'GrantSpace',
      description: '73-minute video on strategies for \'impact without burnout.\' Offers tips for self-care in the non-profit sector.',
      url: 'http://grantspace.org/tools/multimedia/video/the-happy-healthy-nonprofit-strategies-for-impact-without-burnout-2017-02-02',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 31,
      team_id: 1,
      title: 'CU Learn',
      description: 'In-person training and online training through Cornell that aims to ensure safety at the workplace. No cost, but class availability varies (ex: Office Worker Safety, Cornell University Health and Safety Basics, etc.).',
      url: 'http://culearn.cornell.edu/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 32,
      team_id: 1,
      title: 'Cornell IT Resources - Security & Policy',
      description: 'CCE follows Cornells electronic security policy and procedures.  Cornells IT department has a page with information for staff to become acquainted with Cornells practices and resources.',
      url: 'https://it.cornell.edu/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 33,
      team_id: 1,
      title: 'Skillport - IT Skills: Security',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: IT Security for End Users: Using Corporate Devices Securely; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 34,
      team_id: 1,
      title: 'Skillport - Business Skills: Human Resources',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Workplace Management: Risk Management; Risk Management: Organizational Risk and Safety and Health Legislation',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 35,
      team_id: 1,
      title: 'Multicultural Resource Center (MRC) Talking Circles',
      description: 'Highly regarded facilitated dialogues to help participants learn about and dismantle systemic racism, build strategies for resistance and alternatives, and promote healing',
      url: 'http://multiculturalresourcecenter.org/talkingcircles/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 36,
      team_id: 1,
      title: 'Natural Leaders Initiative (NLI) Workshops',
      description: 'NLI offers a variety of highly praised workshops related to building diverse relationships, cultivating diverse participation and leadership, leveraging the power of diverse teams, and more. Check website for information on upcoming workshops or email <natural.leaders@cornell.edu>.',
      url: 'http://ccetompkins.org/community/natural-leaders-initiative/programs-for-community-groups-and-organizations',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 37,
      team_id: 1,
      title: 'CCE Administration \'Opening Doors\' Workshop',
      description: 'Opening Doors (offered on the Cornell campus) is a highly valued, time-tested workshop model for creating a climate for constructive change on diversity for individuals and organizations. Opening Doors offers a foundational understanding of diversity that supports staff in developing a deeper awareness, understanding and skills for effectively working across differences. Cost is $495.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Course-Description2.aspx?courseid=136',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.705Z',
      updated_at: '2017-10-24T18:33:08.705Z'
    },
    {
      id: 38,
      team_id: 1,
      title: 'Human Services Coalition of Tompkins County (HSC-TC) Workshops',
      description: 'HSC-TC offers a variety of workshops throughout the year on diversity, equity and inclusion. Check their website for schedule and cost. Examples: From Micro-Aggressions to Equity; Cultural Competency',
      url: 'http://hsctc.org/index.php?page=training',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 39,
      team_id: 1,
      title: 'Tompkins County Diversity Consortium Roundtable',
      description: 'Bi-annual conference that offers multiple presentations on diversity related topics',
      url: 'http://diversityconsortium.org/home.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 40,
      team_id: 1,
      title: 'Opening Doors',
      description: 'Understanding differences is a key characteristic of diversity competency. Opening Doors is a highly valued, time-tested workshop model for creating a climate for constructive change on diversity for individuals and organizations. Opening Doors offers a foundational understanding of diversity that supports staff in developing a deeper awareness, understanding and skills for effectively working across differences. The registration cost for the workshop is $495 and includes all workshop materials, lodging and food.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Course-Description2.aspx?courseid=136',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 41,
      team_id: 1,
      title: 'CCE Administration Diversity Resources',
      description: 'CCE Administration has multiple resources for understanding and developing relationships with diverse communities.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/prof_courses.aspx?top=Diversity%20Awareness%20and%20Inclusion',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 42,
      team_id: 1,
      title: 'Hiring with a Diversity Lens',
      description: 'On-site training provided to all CCE-Tompkins staff involved in the hiring processes. Offered on an as needed/ requested basis onsite by HR.',
      url: 'Contact HR staff. ',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 43,
      team_id: 1,
      title: 'Excellence & Diversity - A Guide for Search Committees',
      description: 'An excellent written resource with information on attending to issues of diversity and inclusion in all stages of the hiring practice',
      url: 'Contact Margo Hittleman to borrow a copy.',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 44,
      team_id: 1,
      title: 'Human Services Coalition of Tompkins County (HSCTC) Workshops',
      description: 'HSC-TC offers a variety of workshops throughout the year on diversity, equity and inclusion. Check their website for schedule and cost. Examples: From Micro-Aggressions to Equity; Cultural Competency',
      url: 'http://hsctc.org/index.php?page=training',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 45,
      team_id: 1,
      title: 'TC3Biz',
      description: 'TC3Biz sometimes offers a course of managing different generations in the workplace. Check catalogue for current offerings. Fee.',
      url: 'http://www.tc3.edu/biz/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 46,
      team_id: 1,
      title: '[resources needed]',
      description: null,
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 47,
      team_id: 1,
      title: 'Human Services Coalition of Tompkins County Workshops',
      description: 'HSC-TC offers a variety of workshops throughout the year on diversity, equity and inclusion. Check their website for schedule and cost. Examples: From Micro-Aggressions to Equity; Cultural Competency',
      url: 'http://hsctc.org/index.php?page=training',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 48,
      team_id: 1,
      title: 'CCETC Family & Community Development \'P.S. It Works!\' Training',
      description: 'Workshop presented by CCE Tompkins Parenting Program that helps participants develop new tools for communication and fine tune tools you already have',
      url: 'http://ccetompkins.org/family',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 49,
      team_id: 1,
      title: 'CCE Skills for Success',
      description: 'CCE Skills for Success, part of CCETC Position Description, provide guidelines for staff in communication.',
      url: 'http://staff.cce.cornell.edu/ses/WorkersComp/CCE%20Association%20Skills%20for%20Success.pdf',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.706Z',
      updated_at: '2017-10-24T18:33:08.706Z'
    },
    {
      id: 50,
      team_id: 1,
      title: 'CCE Administration Communications Webinars',
      description: 'CCE Administration offers webinars on topics such as: Leading Ourselves, Leading Others, Strategies for Effective Meetings: What Works for You?, Building Collaborative Teams.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/foundations.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 51,
      team_id: 1,
      title: 'Program Development Courses (CCE Administration)',
      description: 'The Program Development Courses offer the following web based training: Writing to Show Impact.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/prog_courses2.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 52,
      team_id: 1,
      title: 'Toast Masters Club',
      description: 'Ithaca Area Toastmasters Club gives its members the opportunity to develop and improve their public speaking abilities through local club meetings, training seminars and speech contests.',
      url: 'http://ithaca.toastmastersclubs.org ',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 53,
      team_id: 1,
      title: 'Kronos Training',
      description: 'CCE Tompkins offers Kronos and Meal Break Training to all new employees (trainings offered bi-monthly by HR).',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 54,
      team_id: 1,
      title: 'Finance Procedures',
      description: 'Links to the most commonly used Finance Forms with instructions regarding policies and procedures',
      url: 'https://mycce.me/content/my-hr-forms-and-tools-for-employee-use',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 55,
      team_id: 1,
      title: 'Skillport - Business Skills: Project Management; Finance and Accounting',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Planning Project Costs; Planning and Preparing an Operating Budget; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 56,
      team_id: 1,
      title: 'CCE Admin Professional Development',
      description: 'CCE Administration offers a variety of grant-writing related workshops. Examples: Grant Writing Introductory Full Day Workshop; Being Strategic with Grant Writing; Planning Your Program for Proposal Writing',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/prof_courses.aspx?top=Grant%20Writing%20and%20Management',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.707Z',
      updated_at: '2017-10-24T18:33:08.707Z'
    },
    {
      id: 57,
      team_id: 1,
      title: 'Human Services Coalition of Tompkins County (HSC-TC)',
      description: 'HSC-TC offers a variety of workshops throughout the year Check their website for schedule and cost. Example: Grantwriting Basics',
      url: 'http://hsctc.org/index.php?page=training',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 58,
      team_id: 1,
      title: 'Free E-book: Grant Writing Revealed',
      description: 'Useful free e-book by local grantwriter & grantwriting instructor Jana Hextor. She also offers a free e-newsletter and blog with tips.',
      url: 'http://grantschampion.com',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 59,
      team_id: 1,
      title: 'Lynda.com - Business: Communication',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Example: Writing Proposals',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 60,
      team_id: 1,
      title: 'Cornell - Mann Library',
      description: 'Cornells Mann Library has many resources, including links to guides for writing federal and state grants, and e-books that can be downloaded and read.',
      url: 'http://guides.library.cornell.edu/funding',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 61,
      team_id: 1,
      title: 'Foundation Center',
      description: 'The Foundation Center has a tremendous amount of online resources, including online funder databases, research tools, and skill-building resources, webinars and other training related to proposal writing, fundraising, organizational sustainability, and management.',
      url: 'http://foundationcenter.org',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 62,
      team_id: 1,
      title: 'Tompkins County Grants Development and Management Center',
      description: 'This Tompkins County government grants development web portal has information on federal, state and private foundation grants, along with many links to excellent resources on grant preparation tools and related training. Most resources are free and available to the public.',
      url: 'http://www.tompkinscountyny.gov/ctyadmin/Grants/index',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 63,
      team_id: 1,
      title: 'CCE Administration Grant Writing Resources',
      description: 'Grant writing resources include Planning your Program for Proposal Writing and Being Strategic with Grant Writing.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/prof_courses.aspx?top=Grant%20Writing%20and%20Management',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 64,
      team_id: 1,
      title: 'Lynda.com - Business: Software',
      description: 'Web-based training videos on many computer application topics from basic to advanced. Free to staff with Cornell NetID.',
      url: 'https://it.cornell.edu/lynda',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 65,
      team_id: 1,
      title: 'Skillport - Desktop Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Using Your Desktop Computer and Devices Safely; Computing Fundamentals (book); Excel 2016; Microsoft Office 2013 Beginning Word',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 66,
      team_id: 1,
      title: 'TC3',
      description: 'Tompkins Cortland Community College offers courses on: Keyboarding for computers, Introduction to Word Processing, Introduction to Spreadsheets, Introduction to Databases, Presentation Software, and Web Page Design. 5-week courses with TC3 enrollment and costs associated.  Courses are in person or web based. Student choice.',
      url: 'https://myinfo.tc3.edu/SelfService/Home.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 67,
      team_id: 1,
      title: 'Working with CCE-Tompkins website (tutorials)',
      description: null,
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 68,
      team_id: 1,
      title: 'Human Service Coalition Workshops',
      description: 'The HSCTC offers workshops on a variety of topics that sometimes include using social media. Small fee.',
      url: 'http://hsctc.org/index.php?page=training',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 69,
      team_id: 1,
      title: 'Alternatives Credit Union Business Courses',
      description: 'Short trainings on a variety of topics that sometimes include using social media. Small fee.',
      url: 'http://www.businesscents.org/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 70,
      team_id: 1,
      title: 'Skillport - IT Skills; Business Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Building Dynamic Web Sites; Digital Marketing: Getting to the Customer',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 71,
      team_id: 1,
      title: 'Lynda.com - Software',
      description: 'Web-based training videos on designing and implementing online instruction, using a variety of apps. Free to staff with Cornell NetID.',
      url: 'https://it.cornell.edu/lynda',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.708Z',
      updated_at: '2017-10-24T18:33:08.708Z'
    },
    {
      id: 72,
      team_id: 1,
      title: 'Skillport - Information Technology Application; Desktop Skills; IT Skills',
      description: 'Web-based training videos on many technology-based tools. Free to staff with Cornell NetID.',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 73,
      team_id: 1,
      title: 'Skillport - Business Skills: Project Management; Professional Effectiveness',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Personal Productivity: Self Organization and Overcoming Procrastination; Quality Management for Continuous Improvement',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 74,
      team_id: 1,
      title: 'Skillport - Business Skills: Professional Effectiveness',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Time Management: Quit Making Excuses and Make Time Instead; Time Management: Ready, Set, Focus; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 75,
      team_id: 1,
      title: 'Natural Leaders Initiative (NLI)',
      description: 'NLI periodically offers a workshop entitled \'Getting Things Done\' which helps build skills to effectively manage ones time and set \'Smart Goals.\' Check NLI website for information on upcoming workshops or email <natural.leaders@cornell.edu>.',
      url: 'http://ccetompkins.org/community/natural-leaders-initiative/programs-for-community-groups-and-organizations',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 76,
      team_id: 1,
      title: 'EAP Training',
      description: 'Employees may attend EAP Seminars on the following topic: Time Management and Achieving Work-Life Balance. Staff can attend at Family and Childrens Services or, if there is enough interest, the programs can be offered on location (there is a cost- $150 per hour if offered onsite).',
      url: 'http://www.fcsith.org/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 77,
      team_id: 1,
      title: 'Skillport - Business Skills: Project Management',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Example: Managing Projects within Organizations',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 78,
      team_id: 1,
      title: 'CCE Supervisor Development Certificate',
      description: 'CCE Supervisor Development Certificate provides guidelines in supervision on a variety of topics related to supervision within the CCE system.',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 79,
      team_id: 1,
      title: 'Skillport - Business Skills: Management; Operations Management',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Coaching Techniques that Drive Change; Six Sigma Team Facilitation and Leadership; Management Essentials: Delegating; Use Delegation to Develop Your Team; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.709Z',
      updated_at: '2017-10-24T18:33:08.709Z'
    },
    {
      id: 80,
      team_id: 1,
      title: 'CCE Administration Reporting Resources',
      description: 'CCE statewide reporting support from CCE Administration -- Webinars & \'virtual office hours\' (weekly during fall reporting season)',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/reporting.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 81,
      team_id: 1,
      title: 'Skillport - Business Skills; Desktop Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Managing Projects within Organizations; Advanced Tools for Managing Multiple Projects; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 82,
      team_id: 1,
      title: 'Skillport - Business Skills: Operations Management; Communications Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Six Sigma Team Dynamics, Roles and Success Factors; Adapting Your Conflict Style; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 83,
      team_id: 1,
      title: 'StrengthsFinder 2.0',
      description: 'StrengthsFinder helps to identify a persons natural strengths and provides descriptions and suggestions to assist personal growth and conflict management.',
      url: 'https://www.amazon.com/StrengthsFinder-2-0-Tom-Rath/dp/159562015X/ref=sr_1_1?s=books&ie=UTF8&qid=1487360256&sr=1-1&keywords=strengths+finder+2.0',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 84,
      team_id: 1,
      title: 'StrengthsFinder 2.0 Team Resources',
      description: 'StrengthsFinder helps to identify a persons natural strengths and provides descriptions and suggestions to assist personal growth and conflict management.',
      url: 'https://www.amazon.com/StrengthsFinder-2-0-Tom-Rath/dp/159562015X/ref=sr_1_1?s=books&ie=UTF8&qid=1487360256&sr=1-1&keywords=strengths+finder+2.0',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 85,
      team_id: 1,
      title: 'Skillport - Business Skills: Human Resources; Operations Management; Communication Skills',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Workplace Management: Corporate Social Responsibility; Six Sigma Team Dynamics, Roles and Success Factors; Adapting Your Conflict Style; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 86,
      team_id: 1,
      title: 'Community Dispute Resolution Center (CDRC)',
      description: 'CDRC offers multiple trainings on mediation/dispute resolution for supervisors and HR level staff.',
      url: 'http://www.cdrc.org/training.html',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 87,
      team_id: 1,
      title: 'Human Services Coalition',
      description: 'HSC-TC workshops available:  Managing Conflict; Improving Your Conflict Confidence); Emotional Intelligence',
      url: 'http://hsctc.org/index.php?page=training',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 88,
      team_id: 1,
      title: 'CCE Administration Program Planning and Development Program',
      description: 'CCE Admin Program Planning and Development: Adult Education Resources',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/planning.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 89,
      team_id: 1,
      title: 'Skillport - Business Skills: Human Resources; Operations Management',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Management of People: Learning and Development; Training and Development; Developing Learning Practices; more',
      url: 'https://it.cornell.edu/skillsoft',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 90,
      team_id: 1,
      title: 'Lynda.com - Education + Elearning; CAD',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Examples: Teaching Techniques: Writing Effective Learning Objectives; Instructional Design Essentials; Universal Principles of Design; Learning How to Increase Learner Engagement; Teaching Complex Topics; more',
      url: 'https://it.cornell.edu/lynda',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 91,
      team_id: 1,
      title: 'CCE Administration Program Planning and Development Resources',
      description: 'CCE Admin Program Planning and Development resources. Examples: Human Participants, Getting Started with Program Evaluation',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/planning.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.710Z',
      updated_at: '2017-10-24T18:33:08.710Z'
    },
    {
      id: 92,
      team_id: 1,
      title: 'Lynda.com - Education + Elearning',
      description: 'Web-based training videos on many topics. Free to staff with Cornell NetID. Example: Measuring Learning Effectiveness',
      url: 'https://it.cornell.edu/lynda',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 93,
      team_id: 1,
      title: 'CCE Program Work Team Website',
      description: 'This website provides links to pages that can provide connections to existing work groups and a way to reach out, as well as tips on building relationships.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/campusconnections.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 94,
      team_id: 1,
      title: 'CCE Administration Diversity Resources - Recruiting and Retaining Diverse Volunteers',
      description: 'CCE Administration provides several resources surrounding recruiting and involving diverse volunteers.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/volunteer.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 95,
      team_id: 1,
      title: 'http://staff.cce.cornell.edu/orgdev/Pages/volunteer.aspx',
      description: 'CCE Administration provides several resources surrounding working with volunteers.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/prof_courses.aspx?top=Volunteer%20Involvement',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 96,
      team_id: 1,
      title: 'Lynda.com - Business; Marketing',
      description: 'Web-based training videos on many topics.  Muliple topics related to marketing. Free to staff with Cornell NetID.',
      url: 'https://it.cornell.edu/lynda',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 97,
      team_id: 1,
      title: 'CCE Supervisor Development Certification',
      description: 'CCE Supervisor Development Certificate provides guidelines in supervision on a variety of topics related to supervision within the CCE system.',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/Course-Description2.aspx?courseid=114',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 98,
      team_id: 1,
      title: 'Cornell and CCE-Tompkins Policies',
      description: 'Links to Cornell University and CCETC policies re: working remotely.',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 99,
      team_id: 1,
      title: 'CCE Training Resources - Tools of the Trade: Foundations & Leadership',
      description: 'Multiple webinars on leadership: Understanding Diverse Personalilities, Making it Work with Diverse Teams, Building Leadership and Developing Communities',
      url: 'http://staff.cce.cornell.edu/orgdev/Pages/foundations.aspx',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.711Z',
      updated_at: '2017-10-24T18:33:08.711Z'
    },
    {
      id: 100,
      team_id: 1,
      title: 'CCE Tompkins Supervisor Training',
      description: 'In-person training with Human Resources - Providing Effective Feedback - contact HR to schedule.',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 101,
      team_id: 1,
      title: 'CCE Tompkins Employee Training',
      description: 'In-person training with Human Resources - CCE TC Hiring Process and Recruitment with an Equity and Inclusion Lens',
      url: '',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 102,
      team_id: 1,
      title: 'Inservice',
      description: 'Agriculture, Food & Environmental Systems conference discussing current developments in practices and research in agriculture. Industry professionals, educators, and faculty from a variety of agricultural fields will be in attendance. Sessions occur every Novemnber. Costs vary depending on number of attendees.',
      url: 'http://cce.cornell.edu/page/inservice',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 103,
      team_id: 1,
      title: 'Cornell Garden-Based Learning',
      description: 'Various resources for horticulture educators. Includes opportunities to join program work teams, volunteer programming, workshops, and participation in emerging statewide projects. Cornell Garden-Based Learning also has social media pages and e-mail lists for relevant horticulture content and news updates.',
      url: 'https://gardening.cals.cornell.edu/for-cce-staff/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 104,
      team_id: 1,
      title: 'Youtube',
      description: 'Youtube playlist from Cornell Garden-Based Learning with webinar recordings of relevant horticulture content and educational materials.',
      url: 'https://www.youtube.com/playlist?list=PLHPXm2Es8aQDjvBs5r3ZXEA4DRBUqiT58',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 105,
      team_id: 1,
      title: 'Agro-One',
      description: 'Soil-testing service that provides soil-sampling supplies and results. Promotes crop management. Soil test results can be obtained through paper, electronically, or via web.',
      url: 'http://dairyone.com/analytical-services/agronomy-services/soil-testing/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 106,
      team_id: 1,
      title: 'Cornell Nutrient Analysis Lab',
      description: 'Soil-testing service offered by Cornell Nutrient Analysis Lab (CNAL). Provides research quality analysis for environmental and biological samples.',
      url: 'https://cnal.cals.cornell.edu/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 107,
      team_id: 1,
      title: 'Cornell Pesticide Management Program',
      description: 'Pesticide information and education center. Provides unbiased information about pests and pesticides to promote best pesticide practices in the state of New York.',
      url: 'http://pmep.cce.cornell.edu/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 108,
      team_id: 1,
      title: 'Program Work Teams',
      description: 'Groups of faculty, staff, extension educators, and external stakeholders who collaborate to identify issues, study needs, and create educational materials. Team members design learning experiences that address issues and needs within specific content areas.',
      url: 'http://cce.cornell.edu/pwts',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 109,
      team_id: 1,
      title: 'Background Reading: Tompkins County and NYS',
      description: 'Contains readings pertaining to energy policy and development in Tompkins County and New York State.',
      url: 'O:\\AEnergyTeam\\Resources-Energy Shared',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 110,
      team_id: 1,
      title: 'Energy Literacy Videos',
      description: 'Topics range from EPA essential energy principles (series of 7 short videos) to videos on solar PV to weatherizations',
      url: 'O:\\Energy Warriors\\Curriculum\\Teaching aids for EW Classes\\Videos',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 111,
      team_id: 1,
      title: 'ACT for Youth - Youth Development',
      description: 'ACT (Assets Coming Together) for Youth Center of Excellence connects research to practice in the areas of positive youth development and sexual health. With support from the NYS Department of Health, it provides resources to aid those working in the areas of youth development and adolescent sexual health. The website provides information about principles of Youth Development and featured resources.',
      url: 'http://www.actforyouth.net/youth_development/development/',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.712Z',
      updated_at: '2017-10-24T18:33:08.712Z'
    },
    {
      id: 112,
      team_id: 1,
      title: 'ACT for Youth - Youth Development: Positive Youth Development 101',
      description: 'ACT (Assets Coming Together) for Youth Center of Excellence connects research to practice in the areas of positive youth development and sexual health. With support from the NYS Department of Health, it provides resources to aid those working in the areas of youth development and adolescent sexual health. This is a free manual curriculum with activity worksheets, handouts, and slides and offers an orientation to the youth development approach for professionals new to the field of youth work. The 10-hour curriculum is structured in five distinct sections, each of which may be presented as a stand-alone workshop.',
      url: 'http://www.actforyouth.net/youth_development/professionals/manual.cfm',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.713Z',
      updated_at: '2017-10-24T18:33:08.713Z'
    },
    {
      id: 113,
      team_id: 1,
      title: 'ACT for Youth - Youth Development: PYD 101 Online Courses',
      description: 'ACT (Assets Coming Together) for Youth Center of Excellence connects research to practice in the areas of positive youth development and sexual health. With support from the NYS Department of Health, it provides resources to aid those working in the areas of youth development and adolescent sexual health. This is a series of short online courses intended to introduce PYD to new youth work professionals. It is based on, and can be used to supplement, Positive Youth Development 101. The courses are stand-alone and interactive and may be taken in any order. Each course can be completed in about 30 minutes. Courses are open to all; registration is required. There are currently four courses available.',
      url: 'http://www.actforyouth.net/youth_development/professionals/online_courses.cfm',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.713Z',
      updated_at: '2017-10-24T18:33:08.713Z'
    },
    {
      id: 114,
      team_id: 1,
      title: 'CITI Cornell University IRB approved assessment for Social and Behavioral Research',
      description: null,
      url: 'https://admin.fnec.cornell.edu/Training_IRB/IRB_Human_Subjects.cfm',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.713Z',
      updated_at: '2017-10-24T18:33:08.713Z'
    },
    {
      id: 115,
      team_id: 1,
      title: 'Six Principles of Adult Learning',
      description: null,
      url: 'O box',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.713Z',
      updated_at: '2017-10-24T18:33:08.713Z'
    },
    {
      id: 116,
      team_id: 1,
      title: 'Seven Key Facilitation Skills',
      description: null,
      url: 'O box',
      review_count: 0,
      review_average: 0,
      created_at: '2017-10-24T18:33:08.713Z',
      updated_at: '2017-10-24T18:33:08.713Z'
    }
  ]
})

export default resourcesFixtures

