- name: create directories
  file:
    path: /var/www/maha/websites
    state: directory
    owner: root
    group: root
    setype: httpd_config_t
    mode: 0755

- name: create directories
  file:
    path: /var/www/maha/websites/default
    state: directory

- name: copy index.html
  copy:
    src: ../files/index.html
    dest: '/var/www/maha/websites/default/index.html'

- name: install libcurl
  yum:
    name: libcurl-devel

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: copy nginx.conf
  copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode:
    backup: yes

- name: reload nginx
  systemd:
    name: nginx
    daemon_reload: yes

- name: enable nginx
  systemd:
    name: nginx
    enabled: yes

- name: start nginx
  systemd:
    name: nginx
    state: started
